### ISSUE TITLE
Install Script Error

### ISSUE THREAD

**Issue by mariocimet** [mariocimet/BraveButtons#1]
Following the instructions so far yields this error at the end:

"Job for networking.service failed because the control process exited with error code.
See "systemctl status networking.service" and "journalctl -xe" for details."

typing in journalctl -xe yields the following:

![image](https://user-images.githubusercontent.com/7051376/43978854-90a3cf78-9c9d-11e8-8eba-2a4b40fa69d7.png)

systemctl status networking.service yields 
![image](https://user-images.githubusercontent.com/7051376/43979845-e8b71ec4-9ca0-11e8-90c4-fda8deb04df4.png)

looks like a problem with 'add bridge' (is that bridge-utils?). I updated it and still have the same issue.

**Comment by schwarrrtz** [comment]
should be fixed as of 8910dadb52c25d41b5c10bc2689535570d661a05

**Comment by mariocimet** [comment]
Cool
